version: "3.7"
services:
  app:
    build:
      args:
        user: florian
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: openmeet
    container_name: openmeet-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - openmeet

  db:
    image: mysql:5.7
    container_name: openmeet-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - openmeet

  nginx:
    image: nginx:alpine
    container_name: openmeet-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - openmeet
      
  adminer:
    image: adminer
    #restart: always
    ports:
      - 8080:8080
    links:
      - db

networks:
  openmeet:
    driver: bridge